CREATE TABLE tx_eudiwalletintegration_configuration (
    uid int unsigned NOT NULL auto_increment,
    pid int unsigned NOT NULL DEFAULT 0,
    tstamp int unsigned NOT NULL DEFAULT 0,
    crdate int unsigned NOT NULL DEFAULT 0,
    cruser_id int unsigned NOT NULL DEFAULT 0,
    deleted smallint unsigned NOT NULL DEFAULT 0,
    hidden smallint unsigned NOT NULL DEFAULT 0,
    title varchar(255) NOT NULL DEFAULT '',
    identifier varchar(120) NOT NULL DEFAULT '',
    mode varchar(32) NOT NULL DEFAULT 'login',
    credential_query_id varchar(80) NOT NULL DEFAULT 'pid',
    vct varchar(255) NOT NULL DEFAULT '',
    purpose text,
    require_holder_binding smallint unsigned NOT NULL DEFAULT 1,
    create_missing_users smallint unsigned NOT NULL DEFAULT 0,
    update_existing_users smallint unsigned NOT NULL DEFAULT 1,
    user_storage_pid int unsigned NOT NULL DEFAULT 0,
    default_usergroup int unsigned NOT NULL DEFAULT 0,
    identity_claim varchar(255) NOT NULL DEFAULT '',
    match_claim varchar(255) NOT NULL DEFAULT '',
    match_field varchar(80) NOT NULL DEFAULT '',
    username_claim varchar(255) NOT NULL DEFAULT '',
    store_verification_result smallint unsigned NOT NULL DEFAULT 0,
    PRIMARY KEY (uid),
    KEY parent (pid),
    KEY identifier (identifier)
);

CREATE TABLE tx_eudiwalletintegration_claim_mapping (
    uid int unsigned NOT NULL auto_increment,
    pid int unsigned NOT NULL DEFAULT 0,
    tstamp int unsigned NOT NULL DEFAULT 0,
    crdate int unsigned NOT NULL DEFAULT 0,
    cruser_id int unsigned NOT NULL DEFAULT 0,
    deleted smallint unsigned NOT NULL DEFAULT 0,
    hidden smallint unsigned NOT NULL DEFAULT 0,
    configuration int unsigned NOT NULL DEFAULT 0,
    sorting int unsigned NOT NULL DEFAULT 0,
    claim_name varchar(255) NOT NULL DEFAULT '',
    target_field varchar(80) NOT NULL DEFAULT '',
    required smallint unsigned NOT NULL DEFAULT 1,
    overwrite_existing smallint unsigned NOT NULL DEFAULT 1,
    PRIMARY KEY (uid),
    KEY parent (pid),
    KEY configuration (configuration)
);

CREATE TABLE tx_eudiwalletintegration_trust_anchor (
    uid int unsigned NOT NULL auto_increment,
    pid int unsigned NOT NULL DEFAULT 0,
    tstamp int unsigned NOT NULL DEFAULT 0,
    crdate int unsigned NOT NULL DEFAULT 0,
    cruser_id int unsigned NOT NULL DEFAULT 0,
    deleted smallint unsigned NOT NULL DEFAULT 0,
    hidden smallint unsigned NOT NULL DEFAULT 0,
    configuration int unsigned NOT NULL DEFAULT 0,
    sorting int unsigned NOT NULL DEFAULT 0,
    issuer varchar(500) NOT NULL DEFAULT '',
    key_id varchar(255) NOT NULL DEFAULT '',
    authority_key_identifier varchar(255) NOT NULL DEFAULT '',
    public_key_path varchar(1024) NOT NULL DEFAULT '',
    x509_trust_anchor_path varchar(1024) NOT NULL DEFAULT '',
    allowed_algorithms varchar(255) NOT NULL DEFAULT 'ES256',
    PRIMARY KEY (uid),
    KEY parent (pid),
    KEY configuration (configuration)
);

CREATE TABLE tx_eudiwalletintegration_session (
    uid int unsigned NOT NULL auto_increment,
    session_id varchar(80) NOT NULL DEFAULT '',
    state varchar(160) NOT NULL DEFAULT '',
    response_encryption_kid varchar(128) NOT NULL DEFAULT '',
    configuration_uid int unsigned NOT NULL DEFAULT 0,
    session_json mediumtext,
    status varchar(32) NOT NULL DEFAULT '',
    version int unsigned NOT NULL DEFAULT 1,
    browser_token_hash char(64) NOT NULL DEFAULT '',
    browser_consumed smallint unsigned NOT NULL DEFAULT 0,
    same_device smallint unsigned NOT NULL DEFAULT 0,
    same_device_confirmed smallint unsigned NOT NULL DEFAULT 0,
    response_code_hash char(64) NOT NULL DEFAULT '',
    response_code_consumed smallint unsigned NOT NULL DEFAULT 0,
    return_url text,
    return_mode varchar(32) NOT NULL DEFAULT 'page',
    fe_user_uid int unsigned NOT NULL DEFAULT 0,
    created_at int unsigned NOT NULL DEFAULT 0,
    expires_at int unsigned NOT NULL DEFAULT 0,
    updated_at int unsigned NOT NULL DEFAULT 0,
    PRIMARY KEY (uid),
    UNIQUE KEY session_id (session_id),
    UNIQUE KEY state (state),
    KEY response_encryption_kid (response_encryption_kid),
    KEY status (status),
    KEY configuration_uid (configuration_uid),
    KEY expires_at (expires_at)
);

CREATE TABLE tx_eudiwalletintegration_identity (
    uid int unsigned NOT NULL auto_increment,
    identity_hash char(64) NOT NULL DEFAULT '',
    fe_user_uid int unsigned NOT NULL DEFAULT 0,
    issuer varchar(500) NOT NULL DEFAULT '',
    subject varchar(500) NOT NULL DEFAULT '',
    identity_source varchar(300) NOT NULL DEFAULT '',
    credential_type varchar(500) NOT NULL DEFAULT '',
    created_at int unsigned NOT NULL DEFAULT 0,
    last_verified_at int unsigned NOT NULL DEFAULT 0,
    PRIMARY KEY (uid),
    UNIQUE KEY wallet_identity (identity_hash),
    KEY fe_user_uid (fe_user_uid)
);

CREATE TABLE tx_eudiwalletintegration_verification (
    uid int unsigned NOT NULL auto_increment,
    session_id varchar(80) NOT NULL DEFAULT '',
    configuration_uid int unsigned NOT NULL DEFAULT 0,
    fe_user_uid int unsigned NOT NULL DEFAULT 0,
    verified_at int unsigned NOT NULL DEFAULT 0,
    issuer varchar(500) NOT NULL DEFAULT '',
    subject varchar(500) NOT NULL DEFAULT '',
    credential_type varchar(500) NOT NULL DEFAULT '',
    claims_json mediumtext,
    mapped_fields_json text,
    PRIMARY KEY (uid),
    KEY session_id (session_id),
    KEY configuration_uid (configuration_uid),
    KEY fe_user_uid (fe_user_uid)
);
