services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  T3Hub\EudiWalletIntegration\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'

  Eudi\QrCode\QrCodeRendererInterface:
    class: Eudi\QrCode\SvgQrCodeRenderer

  T3Hub\EudiWalletIntegration\Contract\AgeOver18VerificationInterface:
    alias: T3Hub\EudiWalletIntegration\Service\AgeOver18VerificationService

  T3Hub\EudiWalletIntegration\Service\ClaimProviderInterface:
    alias:
      T3Hub\EudiWalletIntegration\Service\WalletClaimService